version: '2'
services:
  ui:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'